### ISSUE TITLE
TradeNote in Unraid 7.0 (Docker)

### ISSUE THREAD

**Issue by Helios12345** [Eleven-Trading/TradeNote#106]
Hi,

have you ever tried to get TradeNote running on Unraid?
Wanna write a short tutorial maybe?
This would be so awesome.

Thanks!

I have a MondoDB running on Port 27017.

At the moment I get these errors:

MongoServerSelectionError: getaddrinfo ENOTFOUND mongo
    at Timeout._onTimeout (/app/node_modules/parse-server/node_modules/mongodb/lib/sdam/topology.js:278:38)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) { 'mongo:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: null,
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined,
  [Symbol(errorLabels)]: Set(0) {}
}
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

MongoServerSelectionError: getaddrinfo ENOTFOUND mongo
    at Timeout._onTimeout (/app/node_modules/parse-server/node_modules/mongodb/lib/sdam/topology.js:278:38)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      'mongo:27017' => ServerDescription {
        address: 'mongo:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 523224266,
        lastWriteDate: 0,
        error: MongoNetworkError: getaddrinfo ENOTFOUND mongo
            at connectionFailureError (/app/node_modules/parse-server/node_modules/mongodb/lib/cmap/connect.js:367:20)
            at Socket.<anonymous> (/app/node_modules/parse-server/node_modules/mongodb/lib/cmap/connect.js:290:22)
            at Object.onceWrapper (node:events:632:26)
            at Socket.emit (node:events:517:28)
            at emitErrorNT (node:internal/streams/destroy:151:8)
            at emitErrorCloseNT (node:internal/streams/destroy:116:3)
            at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
          cause: Error: getaddrinfo ENOTFOUND mongo
              at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
            errno: -3008,
            code: 'ENOTFOUND',
            syscall: 'getaddrinfo',
            hostname: 'mongo'
          },
          [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
        },
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        '$clusterTime': null
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: null,
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined,
  [Symbol(errorLabels)]: Set(0) {}
}

Node.js v18.20.5
STARTING NODEJS SERVER

STARTING PARSE SERVER
warn: DeprecationWarning: The Parse Server option 'encodePars

![image](https://github.com/user-attachments/assets/6e887baf-a0cb-4e1a-bc17-585b5f1227aa)

**Comment by Helios12345** [comment]
MONGO_URI:
mongodb://tradenote:tradenote@mongo:27017/tradenote?authSource=admin

**Comment by Helios12345** [comment]
http://192.168.1.130:8811 (configured Port) does not work

**Comment by Helios12345** [comment]
Wrong config?

**Comment by 7aklhz** [comment]
Hi. All installation issues are treated in the Discord channel. Please post your issue their.

**Comment by 7aklhz** [comment]
Hi. All installation issues are treated in the Discord channel. Please post your issue their.

**Comment by Helios12345** [comment]
It's working out of the box (only change Host Port) with Docker Compose in Unraid!
Can be closed
